### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by MattiasNilsson**

### CODE REVIEW

**Comment by cundd** [comment]
Hy! Thank you for the PR. 
I'm curious: Why are you submitting formatting changes? Do you've got a build server which is complaining?

**Comment by MattiasNilsson** [comment]
First of all it was to streamline with the rest of the code and secondly to make it also more readable.

**Comment by cundd** [comment]
:+1: nice!

Eventually I'll move on to PSR-2 coding style, but I haven't found the time yet.

**Comment by cundd** [comment]
I made a very small change to the logged message. I'm no native speaker but I think it should be that way.

Thank you for the improvements

**Pull request merged**
