### PR TITLE
Allow NULL for the `tx_rest_apikey` in v3 branch

### PR DESCRIPTION
**Pull request by mabolek**
Replicating commit 664f2d1 in branch v3 (#62)

### CODE REVIEW

**Comment by cundd** [comment]
Thank you for your PR!

Could you possibly Rebase your change on the latest commit (in which the Travis tests should be fixed)

**Comment by mabolek** [comment]
@cundd Now you have it. All green.

**Comment by cundd** [comment]
Perfect

**Comment by sneopu** [comment]
Would it be possible to release a v3.6.1 with this fix?

**Comment by cundd** [comment]
@sneopu thank you for the reminder. The release has been tagged and uploaded to TER.

**Comment by sneopu** [comment]
@cundd Perfect. Thanks a lot for this super fast service.

**Pull request merged**
