### PR TITLE
Request::getSentData can be called twice

### PR DESCRIPTION
**Pull request by stuartmcfarlane**
In the case of application/json data being PUT or PATCHED Request was using
`(string)$this->getBody()` to fetch the payload for json_decoding. Unfortunately
this consumes the Stream and subsequent calls return nothing.

With this commit the sentData is cached in the Request object and returned on
subsequent calls

### CODE REVIEW

**Comment by cundd** [comment]
Thank you Stuart for the pull request. There seem to be a problem with the Request Unit Test. I think the build error is thrown because the test request doesn't "send" the headers to trigger the `json_decode()` in your PR.

This brings me to another point: Decoding the JSON only if the headers say so, would break backwards compatibility. Should we delay the header check to a later version?

**Comment by stuartmcfarlane** [comment]
The reason I only decoded the json when the content type is application/json was if the contect type was form encoded for example, the catt to getParsedBody returned garbage.

A different check might be more appropriate. Not sure what though

**Comment by stuartmcfarlane** [comment]
I could reverse the logic and do the `json_decode` only of the content type isn't `application/x-www-form-urlencoded` or `multipart/form-data`

**Comment by cundd** [comment]
That's good idea!

Could you have a look at the Unit Tests nevertheless? You can run them with `bash Build/test.sh`

**Comment by stuartmcfarlane** [comment]
Take a look at this. Here is the code from the typo3 core function ServerRequestFactory::fromGlobals that populates Request::parsedBody:

```
        $parsedBody = GeneralUtility::_POST();
        if (empty($parsedBody) && in_array($method, ['PUT', 'PATCH', 'DELETE'])) {
            parse_str(file_get_contents('php://input'), $parsedBody);
        }
```

For a `PUT`, `PATCH` or `DELETE` the `parsedBody` of a request will be correct only if the body is  `application/x-www-form-urlencoded` or `multipart/form-data`. The `content-type` header is completely ignored. The result of this is if you `PUT`, `PATCH` or `DELETE` with JSON in the body it will be incorrectly parsed into `parsedBody`, even if you specify the `content-type` as `application/json`.

An example of the result of `parse_str()` on JSON input is

```
   parse_str('{"a":1,"b":2}', $parsedBody);

==> 
[
   "\"a\":1,\"b\":2" => ""
]
```

This is clearly not what we implementors of REST APIs are interested in.

So, we should treat `Request::parsedBody` with some scepticism and prefer our own implementation of the parsing of the request's body.

While I am not ruling out the fact that my implementation of `getSentData()` may have errors I think that the fact that your tests fail when the body is correctly parsed indicates that your tests are making broken assumptions.

If you agree with my analysis above then would you take a new look at your tests and the implementation `getSentData` in the light of this perhaps new information.

**Comment by cundd** [comment]
Thank you for the detailed investigation!

I've updated the Unit Tests to reflect the your implementation.

**Comment by cundd** [comment]
I merged the Pull Request, but it looks like it also broke the authentication. I'll have a deeper look at it.

**Pull request merged**
